const {chromium}=require('C:/Users/Elias Queiroz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[],external=[];const c=await browser.newContext({viewport:{width:412,height:915},deviceScaleFactor:2,hasTouch:true,isMobile:true,acceptDownloads:true});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});await p.goto(pathToFileURL(path.join(__dirname,'Guedala_Park_Interativo.html')).href);await p.waitForSelector('#scene[data-rendered]');
 const rooms=await p.evaluate(()=>GuedalaStudy.project.rooms.map(r=>r.id));
 for(const room of rooms){await p.evaluate(r=>GuedalaStudy.setRoom(r),room);for(const view of['top','iso','side']){await p.evaluate(v=>GuedalaStudy.setView(v),view);await p.waitForTimeout(40);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,room+'/'+view+' overflow');}}
 await p.evaluate(()=>{GuedalaStudy.setRoom('sala');GuedalaStudy.setView('iso');});
 await p.selectOption('#sofaState','open');await p.waitForTimeout(50);assert.match(await p.locator('#metrics').innerText(),/72 cm/);
 await p.locator('#sofaGap').evaluate(e=>{e.value='5';e.dispatchEvent(new Event('input'));});assert.match(await p.locator('#metrics').innerText(),/67 cm/);
 await p.locator('#sofaGap').evaluate(e=>{e.value='0';e.dispatchEvent(new Event('input'));});
 await p.selectOption('#sofaState','storage');await p.selectOption('#dryState','low');await p.selectOption('#officeState','guest');await p.selectOption('#diningState','stored');await p.selectOption('#consoleState','escritorio');await p.waitForTimeout(60);
 const counts=await p.evaluate(()=>{const n=GuedalaStudy.buildScene();return{ps5:n.filter(o=>o.id==='ps5').length,chairs:n.filter(o=>o.id==='diningchairs').length,officeChair:n.filter(o=>o.id==='officechair').length,box:n.filter(o=>/box|caixa/i.test(o.id||'')).length,finite:n.flatMap(mesh).every(f=>f.p.every(p=>p.every(Number.isFinite)))};});assert.equal(counts.ps5,1);assert.equal(counts.chairs,3);assert.equal(counts.officeChair,1);assert.equal(counts.box,0);assert.equal(counts.finite,true);
 // True touch input through Chromium's input stack.
 const stage=await p.locator('#scene').boundingBox();await p.locator('#scene').scrollIntoViewIfNeeded();const box=await p.locator('#scene').boundingBox(),x=box.x+box.width/2,y=box.y+box.height/2;const cd=await c.newCDPSession(p);const before=await p.evaluate(()=>GuedalaStudy.state.angle);
 await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+40,y:y+5,id:1}]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await p.evaluate(()=>GuedalaStudy.state.angle),before);
 const zoom=await p.evaluate(()=>GuedalaStudy.state.zoom);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-30,y,id:1},{x:x+30,y,id:2}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-55,y,id:1},{x:x+55,y,id:2}]});await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await p.evaluate(()=>GuedalaStudy.state.zoom)>zoom);
 await p.evaluate(()=>GuedalaStudy.selectItem('wardrobe'));await p.locator('.ward-detail summary').click();assert.equal(await p.locator('.ward-detail img').evaluate(e=>e.complete&&e.naturalWidth>0),true);await p.locator('#closeInfo').click();
 for(const tab of['mood','decisions']){await p.locator('[data-tab="'+tab+'"]').click();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 const downloading=p.waitForEvent('download');await p.locator('#downloadHTML2').click();const d=await downloading;const temp=path.join(__dirname,'Copia_validada.html');await d.saveAs(temp);await p.goto(pathToFileURL(temp).href);await p.waitForSelector('#scene[data-rendered]');assert.equal(await p.locator('#sofaState').inputValue(),'closed');assert.equal(await p.evaluate(()=>GuedalaStudy.state.room),'all');
 await p.setViewportSize({width:915,height:412});await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:path.join(__dirname,'Paisagem_mobile.png')});
 assert.equal(errors.length,0,errors.join(';'));assert.equal(external.length,0,'offline dependencies');await browser.close();const report={result:'PASSOU',viewports:['1440×1100','412×915 toque','915×412 paisagem'],checks:['21 combinações ambiente/vista','72 cm aberto /67 cm com recuo5','1 PS5,3 cadeiras e nenhuma caixa','rotação por toque','pinça para zoom','interior R02 incorporado','cópia HTML reaberta','sem requisições de rede','sem erro JavaScript ou overflow'],counts,errors,external};fs.writeFileSync(path.join(__dirname,'Verificacao_completa_R01.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));fs.unlinkSync(temp);
})().catch(e=>{console.error(e);process.exit(1);});
