// Estudo local em centímetros. Sem dependências ou consulta externa.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const g = { room:[230,295], bed:[2,110,142,292], sofa:[2,152,92,292], chairGuest:[150,75,224.5,148], chairDaily:[112.75,80,187.25,153], desk:[15,0,215,70], store:[205,165,230,210], hinge:[220,295], tvFront:218, tvBottom:81, stoolHeight:75, supportHeight:3, pull:15 };
const overlaps=(a,b)=>a[0]<b[2]&&a[2]>b[0]&&a[1]<b[3]&&a[3]>b[1];
const distance=(p,r)=>Math.hypot(Math.max(r[0]-p[0],0,p[0]-r[2]),Math.max(r[1]-p[1],0,p[1]-r[3]));
// Distância ao disco inteiro é uma verificação conservadora do setor da porta.
let minDoor=Infinity, collisions=0;
for(let i=0;i<=150;i++) {
  const d=i/10, r=[g.store[0]-d,g.store[1],g.store[2]-d,g.store[3]];
  minDoor=Math.min(minDoor,distance(g.hinge,r));
  for(const o of [g.bed,g.chairGuest,g.desk]) if(overlaps(r,o)) collisions++;
}
const sofaClearance=205-(87+Math.hypot(45,70));
assert(sofaClearance>34.78);
const result={sofaRigidTurnClearance:sofaClearance, units:'cm', geometry:g, storedPassage:g.store[0]-g.bed[2], extractionPassage:g.store[0]-g.pull-g.bed[2], dailyExtractionGap:g.store[0]-g.pull-g.sofa[2], tvGap:g.tvBottom-g.stoolHeight-g.supportHeight, tvHorizontalClearance:g.tvFront-(g.store[2]-g.pull), minDoorDistance:minDoor, doorGap75:minDoor-75, doorGap80:minDoor-80, oldReserveOverlap:85-g.tvBottom, collisions, samples:151, status:'Candidato condicional: guarda e retirada reta do objeto apenas; pessoa e mecanismo de abertura do sofá não verificados.'};
assert.equal(collisions,0); assert.equal(minDoor,85); assert.equal(result.storedPassage,63); assert.equal(result.extractionPassage,48); assert.equal(result.tvGap,3);
// Confere que o detector rejeita interseção real, sem confundir contato de bordas.
assert(overlaps([0,0,10,10],[9,9,20,20])); assert(!overlaps([0,0,10,10],[10,0,20,10]));
fs.writeFileSync(path.join(__dirname,'Resultados_banquinho.json'),JSON.stringify(result,null,2)+'\n');
const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Banquinho — alternativa sob a TV</title>
<style>body{font:17px/1.55 system-ui;margin:0;background:#f4f1ea;color:#203638}main{max-width:1100px;margin:auto;padding:28px}h1{font-size:32px;line-height:1.2}h2{font-size:22px}.tag{color:#755218;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.card{background:white;border-radius:14px;padding:20px}svg{width:100%;height:auto;display:block}svg text{font:10px system-ui;fill:#203638}button{font:inherit;padding:10px 16px;margin:5px;border:1px solid #276c6e;border-radius:8px;background:white;cursor:pointer}button[aria-pressed=true]{background:#276c6e;color:white}.metric{font-size:26px;font-weight:700}small{display:block}a{color:#146568}table{border-collapse:collapse;width:100%}td,th{padding:9px;border-bottom:1px solid #ddd;text-align:left}@media(max-width:750px){.grid{grid-template-columns:1fr}main{padding:16px}}</style>
<main><p class="tag">30/09/2026 · estudo com documentos locais · sem pesquisa externa</p><h1>Uma alternativa sob a TV — com limites claros</h1><p><strong>Continuação:</strong> <a href="Banquinho_operacao.html">sequência de retirada com gabarito de pessoa e limite na porta</a>. Mantida como candidata secundária.</p><p>O banquinho fechado cabe no envelope estudado. A posição ainda <strong>não está liberada para instalação</strong>: a passagem diminui, a retirada precisa ocorrer primeiro na horizontal e falta conferir a pessoa e o mecanismo de abertura do sofá.</p>
<div class="card"><button id="mode" aria-pressed="true">Cama aberta</button><button id="motion" aria-pressed="false">Ver retirada de 15 cm</button><p id="metric" class="metric"></p><small>Distância entre o envelope do banquinho e a cama/sofá. Não inclui uma pessoa, mãos ou a largura necessária para carregar o objeto.</small></div>
<div class="grid"><section class="card"><h2>Planta · escritório 230 × 295 cm</h2><svg viewBox="-12 -15 265 340" role="img" aria-label="Planta do escritório com reserva do banquinho à direita, cadeira, sofá e giro hipotético da porta"><rect width="230" height="295" fill="#faf9f5" stroke="#203638" stroke-width="2"/><rect x="15" y="0" width="200" height="70" fill="#d9bea0"/><text x="60" y="37">Bancada · profundidade 70</text><rect id="chair" fill="#c1d2d4"/><text x="159" y="104">Cadeira</text><rect id="bed" fill="#d9dee6"/><text id="bedLabel" x="12" y="190">Cama</text><path d="M220 295 L140 295 A80 80 0 0 1 220 215 Z" fill="#eee0c3" opacity=".8"/><text x="151" y="277">Porta: hipótese 80</text><rect x="218" y="115" width="5" height="100" fill="#425865"/><rect x="205" y="165" width="25" height="45" fill="none" stroke="#c27339" stroke-dasharray="3 2"/><rect id="stool" x="205" y="165" width="25" height="45" fill="#d69a60" stroke="#895124"/><path id="arrow" d="M225 190 H195 l5 -4 m-5 4 l5 4" fill="none" stroke="#203638"/><text x="0" y="313">Janela no topo · entrada embaixo · medidas em cm</text></svg><p>Laranja: reserva de <strong>45 × 25 cm</strong>, não um armário novo. Tracejado: posição guardada. Porta de 80 cm é sensibilidade; largura e eixo reais continuam sem cota confirmada.</p></section>
<section class="card"><h2>Elevação · abaixo da TV</h2><svg viewBox="0 0 270 190" role="img" aria-label="Elevação: banquinho com 75 centímetros sobre apoio de 3, topo a 78, TV começando a 81"><path d="M15 166 H255" stroke="#203638"/><rect x="25" y="27" width="200" height="58" fill="#425865"/><text x="50" y="55" style="fill:white">TV · borda inferior de estudo: 81</text><rect x="125" y="88" width="79" height="75" fill="#d69a60"/><rect x="125" y="163" width="79" height="3" fill="#895124"/><text x="132" y="121">Corpo: 75</text><text x="17" y="101">Topo: 78</text><text x="17" y="145">Apoio: até 3</text><text x="17" y="181">Alturas desde o piso · escala horizontal ampliada</text><path d="M115 85 V88 M110 85 H120 M110 88 H120" stroke="#a52c27"/><text x="18" y="77">Folga: apenas 3</text></svg><p>A reserva antiga de <strong>85 cm de altura</strong> ultrapassaria a borda da TV em 4 cm, mesmo apoiada no piso. Este ensaio exige um apoio baixo e liberação para a frente; gancho que dependa de levantar o banquinho não está validado.</p><h2>Retirada testada</h2><p>Puxar 15 cm para o centro do cômodo coloca a face posterior em x=215, 3 cm à frente da projeção x=218 da TV do modelo. Só depois considerar levantar. Suporte articulado, cabos e mãos podem exigir mais curso.</p><p><strong>Não foi testada a rotação do banquinho nem o transporte por uma pessoa.</strong> A folga de 48 cm é residual entre objetos; não comprova acesso fácil com hóspedes.</p></section></div>
<section class="card"><h2>O que a conta resolve</h2><table><tr><th>Conferência</th><th>Resultado</th></tr><tr><td>Guardado, cama aberta</td><td>63 cm residuais; perda de 25 dos 88 cm brutos</td></tr><tr><td>Retirada reta, cama aberta</td><td>48 cm residuais</td></tr><tr><td>Retirada reta, sofá fechado</td><td>98 cm entre os envelopes</td></tr><tr><td>Distância ao giro hipotético da porta</td><td>10 cm para folha 75; 5 cm para folha 80</td></tr><tr><td>Cadeira estacionada nas visitas</td><td>17 cm entre os intervalos longitudinais</td></tr></table><p><strong>Encaminhamento:</strong> manter como candidato para gabarito, sem incluir suporte na marcenaria ou alterar a TV. O giro do sofá fechado já estudado mantém pelo menos 34,8 cm até a reserva do banquinho. Conferir retirada com uma pessoa e mecanismo de abertura antes de escolher esse local. A faixa da lavanderia permanece descartada; não substituir o banquinho nem usar o baú para contornar a exigência de acesso fácil.</p><p><a href="Banquinho_alternativa.md">Memória, hipóteses e roteiro do gabarito</a> · <a href="Resultados_banquinho.json">Contas reproduzíveis</a> · <a href="Operacao_lavanderia.html">Por que a faixa da lavanderia não funciona</a></p></section></main>
<script>const g=${JSON.stringify(g)};let guest=true,pulled=false;const set=(id,r)=>{const e=document.getElementById(id);['x','y','width','height'].forEach((k,i)=>e.setAttribute(k,[r[0],r[1],r[2]-r[0],r[3]-r[1]][i]));};function draw(){set('bed',guest?g.bed:g.sofa);set('chair',guest?g.chairGuest:g.chairDaily);set('stool',[205-(pulled?15:0),165,230-(pulled?15:0),210]);document.getElementById('bedLabel').textContent=guest?'Cama aberta':'Sofá fechado';document.getElementById('metric').textContent=(205-(pulled?15:0)-(guest?142:92))+' cm entre os envelopes';document.getElementById('mode').textContent=guest?'Cama aberta':'Sofá fechado';document.getElementById('mode').setAttribute('aria-pressed',guest);document.getElementById('motion').setAttribute('aria-pressed',pulled);document.getElementById('motion').textContent=pulled?'Recolher banquinho':'Ver retirada de 15 cm';document.getElementById('arrow').style.display=pulled?'':'none';}document.getElementById('mode').onclick=()=>{guest=!guest;draw()};document.getElementById('motion').onclick=()=>{pulled=!pulled;draw()};draw();</script></html>`;
fs.writeFileSync(path.join(__dirname,'Banquinho_alternativa.html'),html);
console.log(JSON.stringify(result,null,2));
