const fs=require('node:fs'),path=require('node:path');
const R=JSON.parse(fs.readFileSync(path.join(__dirname,'Resultados_cesto.json'),'utf8'));
const n=x=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(x);
const cargas=R.cargas.map(x=>`<tr><td>${x.massaCestoEConteudo} / ${x.massaFrente} kg</td><td>${n(x.torqueFechadoNm)}</td><td>${n(x.torqueAbertoNm)}</td><td>${n(x.inversaoGraus)}°</td></tr>`).join('');
const html=`<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Cesto: frente e retirada — Guedala Park</title><style>
*{box-sizing:border-box}body{margin:0;color:#233e43;background:#f0f1ea;font:16px/1.6 system-ui,sans-serif}main{max-width:1150px;margin:auto;padding:40px 30px 70px}header{padding-bottom:24px;border-bottom:2px solid #c1cec7}.eyebrow{letter-spacing:2px;font-size:12px;font-weight:750}h1{font-size:42px;line-height:1.2;letter-spacing:-1.5px;margin:13px 0}h2{font-size:25px;line-height:1.3;margin:0 0 15px}p{margin:10px 0 16px}a{color:#397179}.lead{max-width:900px;font-size:20px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:25px 0}.card{background:#dfe8df;border-radius:10px;padding:20px}.big{display:block;font-size:31px;font-weight:750;line-height:1.25}.small{font-size:14px;color:#567075}.sheet{background:white;padding:28px;border-radius:12px;margin:25px 0}.note{border-left:4px solid #b88754;padding:15px 19px;background:#f6ecdd}.control{display:flex;align-items:center;gap:15px;flex-wrap:wrap;background:#edf3f0;padding:15px;border-radius:8px;margin:16px 0}input{width:330px;max-width:100%;accent-color:#416c6c}output{font-weight:750;min-width:64px}.view{overflow:auto}svg{width:100%;min-width:780px;display:block;height:auto}svg text{font:16px system-ui,sans-serif;fill:#284449}.label{font-size:13px}.center{text-anchor:middle}.end{text-anchor:end}.white{fill:#fff}polygon{stroke-linejoin:round}.legend{display:flex;gap:22px;flex-wrap:wrap;font-size:14px}.swatch:before{content:'';display:inline-block;width:13px;height:13px;margin-right:7px;background:var(--c)}table{border-collapse:collapse;width:100%;font-size:15px}th,td{padding:12px;border-bottom:1px solid #dde5e1;text-align:left}th{background:#edf2ed}.table{overflow:auto}.step{font-size:19px;font-weight:650;margin-top:12px}.duo{display:grid;grid-template-columns:1fr 1fr;gap:24px}.duo h3{font-size:18px;margin:8px 0}ul{padding-left:22px}li{margin:7px 0}footer{font-size:13px;color:#5e7575}@media(max-width:720px){main{padding:24px 14px}h1{font-size:33px}.cards,.duo{grid-template-columns:1fr}.sheet{padding:17px}.table table{min-width:560px}}@media print{input{display:none}.sheet{break-inside:avoid}main{padding:0}svg{min-width:0}}
</style><main><header><div class="eyebrow">GUEDALA PARK / DESENVOLVIMENTO / 30 SET 2026</div><h1>Cesto: abrir, retirar, manter</h1><p class="lead">Frente inferior basculante, painel superior removível e um percurso calculado para o saco. Cesto, tanque e acabamento escolhidos preservados.</p><p><a href="Cesto_retirada.md">Memória e requisitos da ferragem</a> · <a href="Resultados_cesto.json">Cálculos</a> · <a href="../Compatibilizacao_2026-09-28/README.md">Rodada anterior</a></p></header>
<div class="cards"><div class="card"><span class="big">45 × 25 × 45</span><span class="small">Cesto externo mantido · cm</span></div><div class="card"><span class="big">−${n(R.comparacaoFrentes[1].avanco-R.giro.frenteYMax)} cm</span><span class="small">Projeção da frente em relação à alta¹</span></div><div class="card"><span class="big">${n(R.giro.folgaPainel)} cm</span><span class="small">Folga global até o painel superior</span></div></div>
<p class="small">¹ Comparação de frentes no mesmo plano proposto de 63 cm, abertas a 55°. Novas cotas são propostas de desenvolvimento; sem liberação de fabricação.</p>
<section class="sheet"><h2>01 / A frente também precisa caber no giro</h2><p>A parte superior fica parada no uso diário. A inferior acompanha o recipiente. O tracejado mostra quanto uma frente alta avançaria.</p><div class="control"><label for="angle">Abertura</label><input id="angle" type="range" min="0" max="55" step="0.5" value="55"><output id="angleOut">55°</output></div><div class="view"><svg id="giro" viewBox="0 0 1030 665" role="img" aria-label="Corte interativo do giro com tanque, frente, painel e rodapé"></svg></div><div class="legend"><span class="swatch" style="--c:#71988c">Cesto / armação</span><span class="swatch" style="--c:#b69b75">Frentes Arenza, cor indicativa</span><span class="swatch" style="--c:#d2e4eb">Tanque</span><span class="swatch" style="--c:#a4a8a3">Hidráulica de teste</span></div><p id="giroStats" class="step"></p><div class="note">O gabinete ilustrativo a 58 cm não cobria o tanque até y=60. O novo corte propõe frente a 63 cm, deixando 1,2 cm entre tanque e face interna do painel. Pedra permanece em 75; base e rodapé ficam recuados até 58.</div></section>
<section class="sheet"><h2>02 / O saco sai inclinado; depois fica em pé</h2><p>Corpo carregado de teste: <b>40 × 20 × 40 cm</b>, com aro hipotético de 1,5 cm e 1 cm de folga por lado. Não é molde nem capacidade útil garantida.</p><div class="control"><label for="stage">Retirada</label><input id="stage" type="range" min="0" max="100" step="1" value="60"><output id="stageOut">60%</output></div><p id="phase" class="step"></p><div class="view"><svg id="saco" viewBox="0 0 1030 665" role="img" aria-label="Percurso em duas etapas para retirar o saco sem atravessar aro ou bancada"></svg></div><p id="bagStats"></p><div class="note"><b>O espaço da pessoa ainda precisa ser conferido.</b> A retirada chega a ${n(R.saco.yMax)} cm da parede; restam ${n(R.saco.saldoSecao)} cm na seção de 154 cm. Isso comprova apenas o envelope no corte. Mãos, alças, roupa irregular e postura lateral não estão modeladas.</div></section>
<section class="sheet"><h2>03 / Cotas que resolvem os conflitos do estudo</h2><div class="table"><table><thead><tr><th>Parte</th><th>Proposta</th><th>Condição</th></tr></thead><tbody><tr><td>Frente inferior</td><td>z=15–67,1 · altura 52,1 cm</td><td>Fica a pelo menos ${n(R.giro.pisoFrente)} cm do piso ao abrir</td></tr><tr><td>Painel superior</td><td>z=67,5–89,7 · altura 22,2 cm</td><td>3 cm de reserva + cerca de 1 cm para variação</td></tr><tr><td>Frente / pedra</td><td>y=63 / y=75 cm</td><td>12 cm de avanço da pedra; estrutura a detalhar</td></tr><tr><td>Base / rodapé</td><td>Até y=58 cm</td><td>Não estender sob o novo giro da frente</td></tr><tr><td>Junta entre painéis</td><td>4 mm de teste</td><td>Pega e ferragens podem mudar a junta</td></tr><tr><td>Saco fora do aro</td><td>44,5 cm na direção inclinada</td><td>36,45 cm à frente + 25,52 cm acima</td></tr></tbody></table></div><p class="small">Coordenadas desde parede e piso. Eixo preservado em y=56/z=12. Nenhuma cota é levantamento do apartamento.</p></section>
<section class="sheet"><h2>04 / Ferragem e manutenção entram na mesma solução</h2><div class="duo"><div><h3>Uso diário</h3><ul><li>Parada e retenção em 55°, com carga cheia e vazia.</li><li>Alças recolhidas durante o giro e engates acessíveis ao abrir.</li><li>Braços para ligar armação à frente afastada 5,2 cm.</li><li>Sem compartilhar a reserva lateral com a mangueira Telca.</li></ul></div><div><h3>Acesso ao sifão</h3><ul><li>Saco removível não basta se a estrutura impedir o serviço.</li><li>Frente inferior e armação desacopláveis pela frente.</li><li>Painel superior removível; apoios do tanque independentes.</li><li>Desmontagem e recolocação demonstradas no protótipo.</li></ul></div></div><p>O peso muda de efeito durante a abertura. Sensibilidade de momento gravitacional no pivô, com massas hipotéticas e distribuição uniforme:</p><div class="table"><table><thead><tr><th>Cesto + conteúdo / frente</th><th>Fechado · N·m</th><th>55° · N·m</th><th>Inversão</th></tr></thead><tbody>${cargas}</tbody></table></div><p class="small">Positivo favorece abrir; negativo fechar. Não são cargas permitidas nem seleção de pistão. Fixações, impactos, esforços de mão e distribuição real ainda precisam de dimensionamento.</p></section>
<footer>5.501 posições de giro e 1.442 do percurso do saco verificadas; seis conferências matemáticas passaram. Figuras sem perfil real de ferragens, apoios ou mangueira. Fontes: documentos locais R04/R05/R08; sem pesquisa comercial nova. <a href="Cesto_retirada.md">Memória completa</a>.</footer></main>
<script>
const R=${JSON.stringify(R)},P=R.premissas,rad=a=>a*Math.PI/180;
const X=y=>65+y*5.5,Y=z=>615-z*5.5,N=x=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(x);
const corners=b=>[[b[0],b[1]],[b[2],b[1]],[b[2],b[3]],[b[0],b[3]]];
const point=(u,v,a)=>[56+u*Math.cos(rad(a))+v*Math.sin(rad(a)),12-u*Math.sin(rad(a))+v*Math.cos(rad(a))];
const poly=(b,a,l=0)=>corners(b).map(([u,v])=>point(u,v+l,a));
const pg=(q,fill,stroke='#43646a',extra='')=>'<polygon points="'+q.map(([y,z])=>X(y)+','+Y(z)).join(' ')+'" fill="'+fill+'" stroke="'+stroke+'" stroke-width="1.5" '+extra+'/>';
const rect=(b,fill,stroke)=>pg(corners(b),fill,stroke);
const text=(y,z,t,cl='')=>'<text x="'+X(y)+'" y="'+Y(z)+'" class="'+cl+'">'+t+'</text>';
const line=(y,z,y2,z2,dash='')=>'<line x1="'+X(y)+'" y1="'+Y(z)+'" x2="'+X(y2)+'" y2="'+Y(z2)+'" stroke="#83928e" '+dash+'/>';
function fixed(){return rect([0,90,75,92],'#dddcd1')+rect(P.tanque,'#d2e4eb','#91a9b0')+rect(P.hidraulica,'#a4a8a3')+rect([24,15,28,63],'#a4a8a3')+rect(P.base,'#b69b75')+rect([56.2,0,58,11],'#b69b75')+rect([61.2,67.5,63,89.7],'#b69b75')+line(0,0,154,0)+line(154,0,154,105)+line(75,0,75,104,'stroke-dasharray="5 5"')+text(0,106,'PAREDE','label')+text(154,106,'LIMITE DA SEÇÃO 154','label end')+text(34,80,'TANQUE','center label')+text(8,58,'conexões','label')+text(8,54,'de teste','label')+text(76,103,'borda da pedra','label')+text(0,-5,'0 · origem', 'label')+text(75,-5,'75', 'label center')+text(154,-5,'154 cm', 'label end');}
const basket=[-25,0,0,45],front=R.frenteLocal;
function updateGiro(){const a=+document.querySelector('#angle').value,cb=poly(basket,a),fb=poly(front,a),max=Math.max(...fb.map(q=>q[0]));document.querySelector('#angleOut').textContent=N(a)+'°';document.querySelector('#giro').innerHTML=fixed()+pg(poly([5.2,3,7,77.7],a),'none','#aaa','stroke-dasharray="7 5"')+pg(cb,'#71988c99')+pg(fb,'#b69b75')+'<circle cx="'+X(56)+'" cy="'+Y(12)+'" r="4" fill="#294d53"/>'+text(54,5,'eixo 56 / 12','label end')+text(108,86,'tracejado: frente alta','label')+text(108,81,'mesmo plano de 63 cm','label');document.querySelector('#giroStats').textContent='Frente até '+N(max)+' cm · saldo após pedra/frente: '+N(154-Math.max(75,max))+' cm.';}
function updateBag(){const stage=+document.querySelector('#stage').value;let q,phase;if(stage<=60){const l=R.saco.extracao*stage/60;q=poly(P.bag,55,l);phase='1 / Sair acompanhando a inclinação · '+N(l)+' de 44,5 cm';}else{const a=55*(1-(stage-60)/40);q=corners([0,0,20,40]).map(([u,v])=>[R.saco.pivot[0]+u*Math.cos(rad(a))+v*Math.sin(rad(a)),R.saco.pivot[1]-u*Math.sin(rad(a))+v*Math.cos(rad(a))]);phase='2 / Endireitar fora do aro · inclinação restante '+N(a)+'°';}const max=Math.max(...q.map(p=>p[0]));document.querySelector('#stageOut').textContent=stage+'%';document.querySelector('#phase').textContent=phase;document.querySelector('#saco').innerHTML=fixed()+pg(poly(basket,55),'#71988c44')+pg(poly(front,55),'#b69b75')+pg(q,'#b88b5999','#986c3d')+text(110,96,'SACO · corpo de teste','label')+line(R.saco.pivot[0],R.saco.pivot[1],R.saco.pivot[0],105,'stroke-dasharray="3 5"');document.querySelector('#bagStats').textContent='Corpo até '+N(max)+' cm da parede · '+N(154-Math.max(R.giro.frenteYMax,max))+' cm após o conjunto, antes da pessoa. A linha pontilhada marca a referência traseira para endireitar.';}
document.querySelector('#angle').addEventListener('input',updateGiro);document.querySelector('#stage').addEventListener('input',updateBag);updateGiro();updateBag();
</script></html>`;
fs.writeFileSync(path.join(__dirname,'Cesto_retirada.html'),html);console.log('Cesto_retirada.html gerado.');
