/* Centímetros. x: esquerda→direita; z: janela do escritório→entrada; y: altura. */
const PROJECT={revision:'R05 · decisões até 18/09/2026',date:'18 setembro 2026',name:'Guedala Park',area:'40,18 m²',unit:'Torre 2 · final 06',ceiling:247,
  note:'Estudo proporcional. Escolha aprovada não significa medida acabada ou fabricação liberada.',
  rooms:[
    {id:'all',name:'Apartamento',sub:'Visão completa',bounds:[-10,-10,750,710],color:'#e8e0d3'},
    {id:'sala',name:'Sala + jantar',sub:'Bonnie, mesa e painel',bounds:[485,175,750,565],color:'#dcc5a2'},
    {id:'quarto',name:'Quarto',sub:'Queen e armazenamento',bounds:[-10,90,250,405],color:'#c4b9a8'},
    {id:'escritorio',name:'Escritório',sub:'Trabalho e hóspedes',bounds:[245,-10,495,305],color:'#748a8f'},
    {id:'cozinha',name:'Cozinha',sub:'Arenza + Azul Petróleo',bounds:[380,530,750,710],color:'#2d4a50'},
    {id:'lavanderia',name:'Lavanderia',sub:'Varal e área de serviço',bounds:[245,530,390,710],color:'#cfcbc0'},
    {id:'banho',name:'Banheiro',sub:'Sauge e greige',bounds:[245,395,475,540],color:'#89957a'}
  ],
  materials:[
    {id:'wood',name:'Greenplac Arenza',color:'#c4a27b',type:'wood',rooms:['cozinha','escritorio','lavanderia','sala','quarto'],status:'Escolhido / referência',note:'Escolhido na cozinha/escritório e testeira. Referência de composição na sala/quarto; amostras a conferir.'},
    {id:'petrol',name:'Guararapes Azul Petróleo',color:'#294b51',type:'solid',rooms:['cozinha'],status:'Escolhido',note:'Superiores contínuos da geladeira ao cooktop; lavanderia em Arenza. Duratex Azul Profundo é alternativa, não substituição aprovada.'},
    {id:'altblue',name:'Duratex Azul Profundo',color:'#263b45',type:'solid',rooms:['cozinha'],status:'Alternativa',note:'Alternativa de chapa à cor principal, ainda não escolhida.'},
    {id:'stone',name:'Granito Branco Itaúnas',color:'#ded7c7',type:'stone',rooms:['cozinha','lavanderia','banho'],status:'Escolhido',note:'Pedra natural; padrão e cor variam por lote.'},
    {id:'paint',name:'Algodão Egípcio',color:'#e6dfd1',type:'solid',rooms:['sala','quarto','escritorio','cozinha','banho'],status:'Escolhido',note:'Tom digital aproximado. Conferir tinta existente, linha e amostra.'},
    {id:'offwhite',name:'Off-white fosco',color:'#eeeae1',type:'solid',rooms:['sala','escritorio','quarto'],status:'Direção aprovada',note:'Frentes lisas e claras. Código de chapa/amostras ainda a definir.'},
    {id:'inox',name:'Inox Look',color:'#aeb5b5',type:'solid',rooms:['cozinha','lavanderia'],status:'Escolhido',note:'Acabamento escolhido para IB6S e LG VC4. Comparar tons e aparência reais entre as marcas antes da compra.'},
    {id:'beige',name:'Bouclê bege-claro · Bonnie',color:'#d9c9b1',type:'fabric',rooms:['sala'],status:'Escolhido',note:'Modelo e versão de referência escolhidos; conferir tecido do vendedor.'},
    {id:'grey',name:'Cinza-claro · Daiane',color:'#aeb1b2',type:'fabric',rooms:['escritorio'],status:'Escolhido',note:'Cinza-claro aprovado; versão comercial e tecido ainda a conferir.'},
    {id:'head',name:'Bege / greige estofado',color:'#c9bbaa',type:'fabric',rooms:['quarto','sala'],status:'Direção / proposta',note:'Cabeceira clara aprovada como composição; banco de jantar ainda sem tecido final.'},
    {id:'sage',name:'Portobello Vivant Sauge Mate',color:'#78846a',type:'tile',rooms:['banho'],status:'Escolhido',note:'RB-01 · 7 × 24,4 cm · parede focal do box.'},
    {id:'greige',name:'Travertino Reale Greige',color:'#c6bcaa',type:'stone',rooms:['banho'],status:'Escolhido',note:'Biancogres PB-01 Satin 90 × 90 cm; PB-01B EXT no box.'},
    {id:'ivory',name:'Eliane Iseo Marfim AC',color:'#dcd4c3',type:'stone',rooms:['lavanderia'],status:'Escolhido',note:'PL-01 · 90 × 90 cm. Entrega cerâmica; este é acabamento de reforma.'},
    {id:'black',name:'Preto / grafite',color:'#282d2e',type:'solid',rooms:['all'],status:'Escolhido',note:'Metais, pedestal, eletrônicos e detalhes.'},
    {id:'vinyl',name:'Tarkett Ambienta Design Olmo · 24192727',color:'#c7ac86',type:'wood',rooms:['sala','quarto','escritorio','cozinha'],status:'Preferência aprovada',note:'Vinílico em toda a casa, exceto banheiro/lavanderia. Olmo é a preferência; Aveia e Bétula ficam para comparar na loja. Amostra e instalação a conferir.'},
    {id:'bathbeige',name:'Bege fosco liso · banheiro',color:'#c9bca8',type:'solid',rooms:['banho'],status:'Direção aprovada',note:'Frentes fechadas, sem ripado nem puxadores salientes. Código da chapa a definir.'},
    {id:'lightwood',name:'Madeira clara · laterais do banheiro',color:'#c8a77d',type:'wood',rooms:['banho'],status:'Direção aprovada',note:'Madeira apenas nas laterais do gabinete e armário espelhado; padrão exato pendente.'}
  ]};
const ITEMS=[];
function item(id,room,name,kind,dimensions,choice,measure,material,source,notes,extra={}){ITEMS.push({id,room,name,kind,dimensions,choice,measure,material,source,notes,...extra});}
item('bonnie','sala','Sofá Bonnie SoftGel · Cama inBox','sofa','180 × 110 fechado / 136 aberto cm','Aprovado','Referência comercial','beige','F126 / F149','Retrátil, reclinável e com baú. Confirmar área útil para dormir, braços, abertura completa e afastamento traseiro. Altura 100 cm apenas gabarito.',{budget:'R$ 3.000 sem frete'});
item('panel','sala','Painel liso da TV','panel','115 cm L · 2 cm P no ensaio','Aprovado','Parcial / hipótese','offwhite','F139 / F149','Parede ~120 cm é estimativa gráfica. Altura do painel 165 cm ilustrativa; confirmar corredor, cortina, montagem e Ambilight.');
item('racks','sala','Uma prateleira acima e outra abaixo da TV','rack','110 × 35 cm inferior / 110 × 25 cm superior · ensaio','Aprovado','Posições a definir','wood','F148 / F149 / F159','A disposição vigente tem uma prateleira acima e outra abaixo da TV, sem gavetas. A implantação anterior com as duas abaixo foi superada; alturas, equipamentos, cargas e fixação ainda precisam de compatibilização.');
item('power','sala','Compartimento da régua','power','20 × 15 × 12 cm · gabarito','Aprovado','Hipótese','wood','F147–149','Oculto, acessível e ventilado, lateral ao console. Tamanho depende da régua e fontes; não ocupar a ventilação do PS5.');
item('tv50','sala','TV 50″ · preferência Ambilight','tv','111,1 × 64,9 × 8,8 cm de referência','Parcial','Modelo candidato','black','F139 / F140','Tamanho e preferência aprovados; Philips 50PUG8100/78 candidata. Modelo não escolhido. Borda inferior 77 cm é hipótese.',{budget:'Até R$ 3.000 · TV apenas'});
item('soundbar','sala','Soundbar futura','soundbar','90 × 10,5 × 7 cm · gabarito','Futuro','Hipótese','black','F137 / F149','Compra adiada. Dimensões ilustrativas; conferir portas, alto-falantes superiores e espaço abaixo da TV.');
item('ps5','sala','PS5 Slim Digital · um aparelho','console','35,8 × 21,6 × 8 cm · sem saliências','Direção aprovada','Referência comercial','offwhite','F96 / F153 / F154','Uso nos dois ambientes. O controle de localização move o mesmo console. Folgas mínimas, apoios e cabos a conferir.');
item('table','sala','Mesa retangular arredondada','table','180 × 75 cm · cantos R15','Aprovado','Projeto aprovado','wood','F145','Pedestal central único preto. Altura 75 cm e coluna/sapata são gabaritos. Recolhimento 2+1 exige cadeiras compactas e base compatível.');
item('bench','sala','Banco reto estofado com baú','bench','180 × 55 cm · altura 90 no ensaio','Aprovado','Dimensões em estudo','head','F25 / F26 / F145','Três pessoas alinhadas, base fechada até o piso e encosto fixo. Estofamento confortável; tecido, base Arenza e acesso interno ainda a detalhar.');
item('diningchairs','sala','Três cadeiras sem braços','chairs','42 × 44 cm recolhidas · gabarito compacto','Aprovado','Modelo não escolhido','head','F143–145','Três sob a mesa em 2+1; no uso seis lugares, três na lateral. Inserção 38 cm e encosto 6 cm são hipóteses, não produto existente.');
item('queen','quarto','Cama queen existente','bed','Reserva 200 × 160 cm · colchão padrão 198 × 158','Existente','Base não medida','offwhite','F128 / F135','Altura total 60 cm no desenho é hipótese. Usuário menciona cama-baú; mecanismo e cabimento da caixa do gabinete não confirmados.');
item('wardrobe','quarto','Guarda-roupa · interior R02','wardrobe','200 × 60 × 240 cm de referência','Aprovado','Envelope a conferir','offwhite','F134 / F135','Metade para cada; quatro gavetas; dez pares até 42; dois casacos longos; cabideiros nominais 261 cm. Portas/ferragens e funcionamento ainda pendentes.');
item('headboard','quarto','Cabeceira estofada clara','headboard','160 × 5 × 115 cm · envelope ilustrativo','Aprovado','Dimensões em estudo','head','F150–152','Apoio estofado escolhido. Espessura a compatibilizar com circulação e conforto. Sem azul nos móveis e sem TV.');
item('bedcabinet','quarto','Armário alto e raso','upper','180 × 25 × 35 cm · cenário','Aprovado','Parcial / hipótese','offwhite','F150 / F152','25 cm de profundidade, base ~205 cm; largura em estudo 180–200. Desenho usa 180 cm e topo 240 cm, sem confirmar teto real.');
item('ledges','quarto','Dois apoios para celular e óculos','ledges','20 × 15 cm úteis cada','Aprovado','Posição a testar','wood','F151 / F152','Pequenos, sem pés/gavetas. Ensaio sobre cantos internos da cama precisa teste de ombros e travesseiros; não autoriza perda da área de dormir.');
item('desk','escritorio','Bancada de trabalho','desk','200 × 70 cm · topo 75 cm no ensaio','Parcial','Largura/altura em estudo','wood','F99','Profundidade 70 cm escolhida. Altura, largura, estrutura e vão real dos braços da cadeira pendentes.');
item('drawers','escritorio','Duas gavetas à esquerda','drawers','40 × 45 × 24 cm total · proposta','Parcial','Dimensões em estudo','wood','F92 / F99','Quantidade/lado/aparência aprovados. Abertura total, pega discreta; não garantir abertura com cama preparada.');
item('setup','escritorio','Notebook + dois monitores + CH360','setup','2 telas 27″ · CH360 21,5 × 42,8 × 43,1 cm','Aprovado','Equipamentos parcialmente medidos','black','F99','Notebook HP à esquerda, monitor principal à direita do secundário, gabinete à direita. Monitores AOC 27/240 Hz; modelos e braços exatos pendentes.');
item('daiane','escritorio','Sofá-cama Daiane cinza-claro','daybed','140 × 90 fechado / 140 × 182 aberto cm','Aprovado','Referência comercial','grey','F92 / F100','Braço junto à parede da porta no cotidiano. Cama gira para abrir rumo à janela. Desenho mostra posições finais, não valida trajetória.',{budget:'Até R$ 1.500'});
item('officechair','escritorio','Cadeira · cenário Ultra Comfort','chair','74,5 × 73 cm · altura 120 ilustrativa','Em estudo','Candidata','black','F89 / F94','Ultra Comfort não escolhida; LiberNovo também candidata. Fica estacionada no escritório durante visitas. Altura mínima dos braços pendente.');
item('officecab','escritorio','Aéreo principal sobre sofá','upper','200 × 35 × 55 cm','Aprovado','Projeto aprovado','offwhite','F155','Base ~192 cm usando teto 247 cm sem folga adicional. Portas de abrir com amortecimento; divisões internas reguláveis. Fixação a conferir.');
item('officeshelf','escritorio','Prateleira alta dos consoles','shelf','110 × 35 cm · topo a 195 cm','Parcial','Altura aprovada','wood','F154 / F155','Altura aprovada por circulação. Largura é reserva de estudo para possível Xbox; sem armário acima. Acesso/carga/posição longitudinal a conferir.');
item('tv43','escritorio','Samsung 43″ existente','tv','97 × 56 × 5 cm · gabarito','Existente','Modelo não informado','black','F94 / F95','Parede oposta ao sofá; posição deslocada para evitar giro da porta é estudo. Medir aparelho e suporte.');
item('wheel','escritorio','Volante e pedais futuros','accessory','Dimensões / guarda pendentes','Futuro','Não dimensionado','black','F92','Logitech pretendido, G29 candidato. Sem módulo baixo adicional. Não desenhado no piso para não inventar local de guarda.');
item('kitchenbase','cozinha','Base da cozinha em Arenza','kitchen','65 cocção + 60 pia + 61,9 preparo · topo 92 cm no ensaio','Aprovado','Detalhamento pendente','wood','F38 / F162','Três gavetas independentes no preparo: talheres e facas, utensílios e temperos. A pia mantém duas portas e duas prateleiras amplas. Pedra Branco Itaúnas, painéis, ferragens, instalações e ergonomia a conferir.');
item('sinkstorage','cozinha','Gabinete da pia · duas prateleiras','storage','60 cm externos · prateleira regulável','Aprovado','Encaixe a conferir','wood','F162 · 15/09','Duas pilhas de panelas no nível superior; pressão compacta e organizador de tampas, frigideira, tábuas e escorredor seco no inferior. Prateleira regulável com topo inicial a ~50 cm do piso: vãos estimados de 26,2 cm embaixo e 21,5 cm acima, antes das instalações. Lixeira comum Biovis 15 L na parede externa do banheiro.');
item('lowdrawer','cozinha','Gaveta baixa contínua com rodas','drawer','121,9 cm externos · 8,2 A × 40,6 P cm úteis no ensaio','Aprovado','Referência de projeto','wood','15/09/2026','Sob gaveteiro e pia, terminando antes do forno. Rodas de silicone, faixa inferior de 18 cm e frente 8 cm recuada atrás das portas. Rodas, guia, estrutura e cabimento dos utensílios ainda a detalhar.');
item('kitchenupper','cozinha','Aéreos A/B/C/D em azul-petróleo','upper','80,1 + 69,7 + 52,2 + 65 cm externos','Aprovado','Cotas em estudo','petrol','F162 · 15/09','Organização interna aprovada: A e D com divisória vertical central e sem prateleiras; B com uma prateleira; C com três, sendo as duas superiores alinhadas a B. Topo a 255 cm e laje a 257 cm são hipóteses. Ventilação, alcance, conteúdo e ferragens continuam a conferir.');
item('fridge','cozinha','Geladeira Electrolux IB6S Inox Look','fridge','60,1 × 74,75 × 186,6 cm · referência da família','Aprovado','Código de compra a conferir','inox','F119 / F160 / F161','Acabamento inox aprovado, substituindo o branco. Reserva de largura 80,1 cm e recuo traseiro de 10 cm são cenário; abertura, medidas do código final e ventilação ainda precisam de validação.');
item('cooktop','cozinha','Cooktop Electrolux KE4GC','cooktop','56 × 46 cm · envelope a conferir','Aprovado','Representação','black','Equipamentos / F102','Quatro bocas, vidro preto. Furação e relação com forno dependem do manual.');
item('oven','cozinha','Forno Venax Totale Nero GIII 50 L','oven','50 × 55 × 35 cm · gabarito','Aprovado','Representação','black','F103','A gás com grill, 127 V. Exige 20 cm entre fundo do cooktop e topo do forno; montagem desenhada é conceitual.');
item('microwave','cozinha','Micro-ondas Electrolux ME23P','microwave','46,1 × 35,2 × 29 cm · referência','Aprovado','Compatibilização pendente','black','F103 / F104 / 15/09','127 V. Mantidos 10 cm acima como escolha de layout, apesar da divergência com os 30 cm do manual; instalação não validada.');
item('hood','cozinha','Depurador Suggar DE61IX','hood','60 cm L · profundidade/altura ilustrativas','Aprovado','Representação','black','F102','Slim de embutir, inox, 127 V. Instalação/folgas a detalhar.');
item('airfryer','lavanderia','Philips Walita RI9252/91','airfryer','26,4 × 36 × 29,5 cm · referência','Aprovado','Uso a compatibilizar','black','F103 / F162','Permanece desligada sobre a pedra da lavanderia; sem roupas no varal, pode ser usada ali. Com roupas, vai temporariamente para a bancada próxima à geladeira. Folgas, calor, tomadas e convivência com a cafeteira ainda a conferir.');
item('coffeemaker','lavanderia','Cafeteira elétrica de café coado','appliance','Modelo e dimensões pendentes','Direção aprovada','Produto não escolhido','black','F162','Lugar habitual sobre a pedra da lavanderia, desligada; uso ali apenas sem roupas no varal. Quando necessário, pode ir temporariamente para a cozinha. Não presumir uso simultâneo com a air fryer.');
item('sink','cozinha','Cuba Tramontina Dora + Apurema','sink','Zona da pia 60 cm · gabarito cuba 43 × 37','Aprovado','Instalação em estudo','stone','F38 / F43 / 15/09','Torneira preta extensível e tábua parcial. Escorredor Mini Plurale grafite definido: usar junto à cuba, saída da bandeja para ela, e guardar limpo e seco no armário inferior. Apoios, sifão e mangueira a conferir.');
item('filter','cozinha','Purificador Electrolux PE12G grafite','filter','16 × 42 × 35 cm','Aprovado','Instalação a conferir','black','15/09/2026','Modelo definido. Água natural, fria e gelada. Referência junto à geladeira; reserva preliminar de 26 × 52 × 57 cm. Conferir alimentação de água, tomada, calor vizinho, acesso ao refil e posição final.',{budget:'Pesquisa até aproximadamente R$ 660'});
item('washer','lavanderia','LG VC4 CV5012PC4 Inox Look','washer','60 × 62 × 85,5 cm · referência da família','Aprovado','Código de compra a conferir','inox','F102 / F158 / F160 / F161','Acabamento inox aprovado, substituindo o branco. Entre o cooktop e o tanque junto à janela; 127 V, 12 kg lavagem / 7 kg secagem. Reserva, porta aberta, pedra independente e instalação ainda a conferir.');
item('laundrybase','lavanderia','Bancada e armazenamento de serviço','kitchen','129 cm de faixa · alturas/profundidades em estudo','Parcial','Hipótese','wood','F107 / F109','Tanque esculpido junto à janela, armário baixo para cesto removível e instalações. Recicláveis na Loop 20 L no chão; Branco Itaúnas/Arenza. Não confundir com tanque fornecido pela construtora.');
item('laundryupper','lavanderia','Superiores da lavanderia em Arenza','upper','Faixa de 133 cm · módulos e alturas em estudo','Aprovado','Hipótese','wood','F158','Transição após o cooktop. Testeira alinhada ao topo da cozinha; espaço do aquecedor e varal preservado como estudo, com ventilação, exaustão e mecanismo a detalhar.');
item('heater','lavanderia','Rinnai E21 GN REU-E211 FEH','heater','35 × 15,7 × 53 cm · referência a conferir','Aprovado','Instalação pendente','offwhite','F106 / F107','Sem módulo Wi-Fi. Ripado e grelhas, exaustão, manutenção e afastamentos não resolvidos.');
item('drying','lavanderia','Varal oculto elevatório','drying','Grelha 100 × 50 cm','Aprovado','Mecanismo em estudo','wood','F109 / F116','Guardado vazio; secagem no alto; baixo à frente da bancada para carregar. Posições ilustrativas: conflito com E21/recolhimento não resolvido.');
item('bathvanity','banho','Gabinete suspenso + Branco Itaúnas','vanity','60 × 45 cm de bancada · tampo a 76,5 cm no estudo','Aprovado','Dimensões em estudo','bathbeige','18/09/2026','Inteiro fechado, bege fosco liso, laterais de madeira clara; sem nichos, ripado ou puxadores salientes. Pedra igual à cozinha. Divisão interna e portas/gavetas ainda não escolhidas. Borda da cuba a 90 cm é proposta para testar conforto.');
item('basin','banho','Cuba Deca Slim branca L.13040.17','sink','40 × 30 × 13,5 cm','Primeira opção aprovada','Encaixe a conferir','offwhite','18/09/2026','Cuba de apoio retangular. Prioridade de limpeza fácil e amplitude. Bancada de 60 × 45 cm é hipótese: 10 cm laterais e 10 atrás + 5 à frente; compatibilizar torneira e armário.');
item('bath tap','banho','Addra Arion Black · bica alta','tap','Altura ~30 cm · desenho de instalação pendente','Aprovado','Instalação a conferir','black','18/09/2026','Água quente e fria. Centralizada atrás da cuba, entre cuba e espelho. Base, alcance, alavanca e fixação ainda precisam de ficha/peça real; modelo representado de forma aproximada.',{budget:'Teto da torneira: R$ 750; oferta final não confirmada'});
item('bathmirror','banho','Armário raso, todo espelhado','upper','60 cm L × 12–15 cm P externos · ensaio','Aprovado','Dimensões e divisões em estudo','lightwood','18/09/2026','Frente inteira espelhada, sem nichos abertos; madeira clara nas laterais. Guarda escovas, pasta, desodorante e pequenos cosméticos. Quantidade de portas/prateleiras não fechada. Liberar torneira e possível descida hidráulica.');
item('bathlight','banho','Luz frontal para maquiagem','lighting','Posições e potência a detalhar','Direção aprovada','Instalação em estudo','offwhite','18/09/2026','Luz frontal difusa junto ao espelho, além da luz quente indireta de ambiente. Faixas laterais são proposta visual. Temperatura exata, luminárias, potência e comandos pendentes.');
item('shower','banho','Box transparente + Addra Livo Black Matte','shower','Faixa 80 × 124 cm brutos · hipótese','Direção aprovada','Box e instalações em estudo','sage','BAN-003 / 18/09/2026','Ducha Livo BRS2003-BK / SKU2193038 escolhida, redonda de 13,2 cm, com desviador e duchinha. Uma única parede verde: fundo/chuveiro; parede da janela clara. Vidro transparente com perfis pretos finos. Abertura, altura e medidas do box pendentes.',{budget:'Teto do conjunto Livo: R$ 850, sem registros/instalação'});
item('bath shelf','banho','Prateleira do box em Branco Itaúnas','shelf','25–30 × 10 cm · proposta','Direção aprovada','Posição e medidas em estudo','stone','18/09/2026','Apoio para shampoo e sabonete. Prateleira escolhida em vez de nicho embutido; não autoriza recorte de parede. É distinta da possível prateleira sobre a caixa do vaso.');
item('bathshaft','banho','Enchimento técnico existente','technical','Geometria e altura não medidas','Entrega','Volume ilustrativo','greige','P01 / 18/09/2026','P01 identifica enchimento. A faixa de 30 cm e altura mostrada são apenas reserva gráfica. Elias informa fechamento de gesso e propõe acessar o ramal quente nessa região; não remover automaticamente nem inferir o traçado exato das tubulações.');
item('toilet','banho','Celite VIP branco · kit 1977230012300','toilet','37,5 L × 59 P × 80 A cm','Aprovado','Esgoto e afastamentos a conferir','offwhite','18/09/2026','Caixa acoplada, assento PP de queda amortecida e Rimless. Substitui Elite. Frente nominal 65 cm na profundidade de 124 cm, ganho de 7 cm sobre Elite; resultado instalado depende de eixo/folga traseira.');
item('hygiene','banho','Ducha higiênica preta quente e fria','shower','Modelo e posição ainda não definidos','Direção aprovada','Percurso e funcionamento pendentes','black','18/09/2026','Com mistura de temperatura e fechamento próprio; posição desenhada é ilustrativa. Orçamento e modelo pendentes. Rinnai E21 exige 3,9 L/min para acionar: conferir fluxo pelo aquecedor, estabilidade e espera pela água quente.');
item('hotwater','banho','Água quente oculta: quatro caminhos em estudo','technical','Enchimento → pia e ducha higiênica','Em estudo','Nenhum percurso aprovado','paint','18/09/2026','Comparados: acima do forro existente; faixa fechada no canto do teto; sob prateleira elevada de pedra; percurso baixo atrás do vaso. Prioridade de estudo: forro existente, com descida junto ao espelho/gabinete. A faixa de gesso é alternativa. Prateleira acima da caixa precisa de nível superior ao tampo de 76,5 cm e acesso à tampa. Não avançar o vaso. Memorial restringe alterações hidráulicas; derivação no enchimento precisa de avaliação técnica.');
item('bathfinish','banho','Algodão Egípcio, teto branco e uma parede verde','finish','Amostras, paginação e áreas a conferir','Direção aprovada','Produtos complementares pendentes','paint','18/09/2026','Paredes fora do box em Algodão Egípcio; teto branco. Vivant Sauge Mate apenas na parede do chuveiro. Parede clara do box, rejunte, tinta e acessórios exatos a definir. Piso Travertino Reale Greige, Satin fora/EXT dentro conforme adequação técnica.');
item('mirror','quarto','Espelho de corpo inteiro Cebrace prata','mirror','50 × 180 cm · 5 mm','Aprovado','Fixação a conferir','inox','15/09/2026','Centralizado na lateral de 60 cm do guarda-roupa, com margens nominais de 5 cm e base a 20 cm do piso. Sem moldura ou bisotê; bordas lapidadas e cantos levemente arredondados. Conferir painel e fixador próprio.');
item('dishrack','cozinha','Escorredor Tramontina Mini Plurale grafite','accessory','27,8 × 19,9 × 12,6 cm · 9 pratos','Aprovado','Guarda a conferir','black','15/09/2026','Referência 61537000. Tradicional compacto, porta-talheres removível e bandeja inclinada. Usar junto à cuba e guardar limpo e seco no gabinete inferior. Substitui a esteira Mimo.');
item('pressurecooker','cozinha','Panela de pressão Vancouver Effect preta','accessory','3 L · 18,1 cm A × 23,1 cm L · Ø 20 cm','Aprovado','Comprimento com cabo a conferir','black','15/09/2026','Tramontina 20593420. Preparo de 1 kg de feijão em mais de uma rodada, respeitando o limite de enchimento. Guarda no nível inferior da pia; conferir manobra e instalações.');
item('trash','cozinha','Lixeira comum Biovis Coleta 15 L','bin','21 × 34 × 47 cm','Aprovado','Implantação a conferir','inox','15/09/2026','Inox escovado, pedal e balde removível. No chão, na parede externa do banheiro, voltada para a mesa, no ponto verde aprovado. Substitui a Loop 12 L. Passagem nominal de ~107 cm até a mesa; conferir rodapé, tampa e pedal.');
item('recycling','lavanderia','Lixeira de recicláveis Tramontina Loop 20 L','bin','29 × 29 × 43,7 cm','Aprovado','Implantação a conferir','inox','15/09/2026','Referência 94547020. Inox polido, pedal, fechamento suave e balde removível. No chão da lavanderia, no ponto vermelho aprovado; libera o armário sob o tanque para o cesto de roupas. Conferir tampa, pedal e circulação.');
const ROOM_NOTES={
all:'Contorno e posições reconstituídos da P01 e estudos locais. Cotas por ambiente preservadas; vãos, espessuras e alturas são cenários. O modelo não certifica manobras nem circulação acessível.',
sala:'Parede da TV ~120 cm é estimativa. Sofá aberto 136 cm requer conferir reclinação completa. Uma prateleira fica acima e outra abaixo da TV; alturas e equipamentos ainda precisam ser compatibilizados. Mesa aprovada; cadeiras e pedestal dependem dos modelos.',
quarto:'Guarda-roupa R02 aprovado. Deslocamento da queen prioriza o armário; faixa de janela estreita aceita. Cabeceira acrescentada precisa confirmar comprimento total da cama.',
escritorio:'Daiane e cadeira mostram posições finais. A cadeira permanece no cômodo com hóspedes. Porta tem margem crítica estimada; módulo da caixa do gabinete foi eliminado.',
cozinha:'Base e organização interna dos aéreos estão aprovadas funcionalmente. IB6S inox, purificador PE12G definido e gaveta baixa com rodas aparecem como referências; medidas, ferragens, ventilação e instalações ainda não liberam fabricação.',
lavanderia:'VC4 inox, tanque junto à janela, superiores Arenza e grelha 100 × 50 cm preservados. Air fryer e cafeteira ficam habitualmente sobre a pedra e só operam ali sem roupas; mecanismo do varal, aparelhos e E21 ainda exigem compatibilização.',
banho:'VIP, Arion, gabinete fechado e espelho raso com luz de maquiagem; uma parede verde. Cuba Slim como primeira opção. Água quente na pia e ducha desejada; quatro percursos em estudo, sem escolha executiva. Bancada, box e porta ainda precisam de medidas reais.'};
const SOURCES=[['P01 · Planta oficial','Contorno, cotas e distribuição original.'],['F126–135','Bonnie e guarda-roupa interno R02.'],['F139–159','TV 50″, mesa e prateleiras acima/abaixo da TV.'],['F150–155','Cabeceira, aéreo do escritório e prateleira dos consoles.'],['F158–161','Correções de implantação e acabamentos Inox Look.'],['F162 · 15/09','Organização da cozinha/lavanderia e rotina dos aparelhos.'],['Consolidação 15/09','Aéreos A/B/C/D, gabinete da pia e gaveta baixa com rodas.'],['F103–116','Equipamentos, limitações de instalação e ciclo do varal.'],['18/09 · banheiro','VIP, Slim, Arion, gabinete/espelho, cores, luz e rotas de água quente.'],['15/09 · pisos','Vinílico, Olmo como preferência; Aveia/Bétula para amostras.']];

const INTERNALS={
 kitchenupper:{title:'Aéreos A/B/C/D · organização aprovada',status:'Organização aprovada; cotas de estudo',diagram:'kitchen',rows:[['A · geladeira','Divisória vertical central; dois compartimentos altos, sem prateleira horizontal.'],['B · micro-ondas','Uma prateleira horizontal regulável; dois níveis de guarda.'],['C · pia','Três prateleiras; quatro níveis. Duas superiores alinhadas à base e à prateleira de B.'],['D · depurador','Divisória vertical central; dois vãos altos; retorno de ar reservado atrás.']],note:'Topos de apoio de C: 155 / 174,8 / 195,8 / 223,4 cm no estudo. Chapas 18 mm e profundidade 35 cm são premissas. Folga escolhida 10 cm sobre o micro-ondas diverge dos 30 cm do manual; instalação não validada.'},
 sinkstorage:{title:'Gabinete da pia · guarda aprovada',status:'Organização aprovada; cabimento a conferir',diagram:'sink',rows:[['Nível superior','Duas pilhas de panelas, cada uma com pequena + média.'],['Nível inferior','Pressão Vancouver Effect 3 L separada; organizador para tampas, frigideira, tábuas e Mini Plurale seco.'],['Prateleira','Regulável, topo inicial próximo de 50 cm do piso. Vãos de 26,2 cm embaixo e 21,5 cm acima no ensaio.'],['Portas e base','Duas portas iguais; sem lixeira interna. Preservar sifão e mangueira da torneira.']],note:'A Biovis 15 L fica no chão. Medir utensílios e instalações antes de concluir capacidade.'},
 kitchenbase:{title:'Gaveteiro da cozinha',status:'Distribuição aprovada; ferragens a detalhar',diagram:'drawers',rows:[['Superior','Talheres e facas.'],['Intermediária','Utensílios de preparo.'],['Inferior','Temperos.']],note:'Três gavetas independentes; largura de 61,9 cm é faixa de estudo, não lista de corte.'},
 lowdrawer:{title:'Gaveta baixa contínua',status:'Direção e recuo aprovados',rows:[['Percurso','Sob gaveteiro e pia, terminando antes do forno.'],['Base','Rodas de silicone e frente 8 cm recuada para os pés.'],['Envelope','Faixa 18 cm; altura útil 8,2 cm e profundidade 40,6 cm calculadas no ensaio.']],note:'Rodas, carga, guia, estrutura e medidas finais pendentes. Cabimento de vassoura, rodo e mop não comprovado.'},
 wardrobe:{title:'Guarda-roupa R02 · interior aprovado',status:'Plano aprovado; medidas/ferragens a conferir',diagram:'wardrobe',rows:[['Divisão','Metade para cada pessoa.'],['Cabides','261 cm nominais de varões; reserva para dois casacos longos.'],['Gavetas','Quatro no total, duas por pessoa, para íntimas e meias.'],['Tênis','Meta de dez pares até 42: três níveis por lado, com 2 +2 +1 pares. Testar organizadores e retirada.']],note:'Envelope 200 ×60 ×240 cm. Portas de correr são proposta; o corte não define ferragem. Varões superiores a 205 cm requerem teste de alcance.'},
 laundrybase:{title:'Gabinete sob o tanque',status:'Uso definido; interior a dimensionar',rows:[['Guarda','Cesto de roupas removível e acesso às instalações.'],['Recicláveis','Loop 20 L no chão; não ocupa o gabinete.']],note:'Sifão, cesto, portas e folgas ainda precisam de medidas. Não inventar divisões aprovadas.'},
 laundryupper:{title:'Superiores da lavanderia',status:'Acabamento e funções definidos',rows:[['Acabamento','Arenza, integrado à testeira.'],['Compatibilização','Preservar varal, ventilação e manutenção do E21.']],note:'Quantidade e posições das divisórias ainda em estudo.'},
 officecab:{title:'Armários do escritório',status:'Prateleiras reguláveis; distribuição em estudo',rows:[['Guarda','Prateleiras internas reguláveis e removíveis nos módulos comuns.'],['Frentes','Portas de abrir, dobradiças com amortecimento e perfil na borda.'],['Composição','Off-white até o gesso, com arremate e folga técnica oculta.']],note:'Sem módulo para a caixa do gabinete na solução vigente. Não fixar divisões como aprovadas antes de detalhar conteúdo.'},
 drawers:{title:'Gavetas do escritório',status:'Frentes e abertura aprovadas',rows:[['Frentes','Arenza, pega discreta na borda.'],['Abertura','Corrediças de abertura total.']],note:'Amortecimento e divisão interna não definidos; preservar espaço dos braços da cadeira.'},
 bathvanity:{title:'Gabinete do banheiro',status:'Fechado e suspenso; interior pendente',rows:[['Aparência','Frentes bege foscas lisas; madeira clara nas laterais.'],['Instalações','Acesso ao sifão e à água quente/fria; possível distribuição para a ducha.']],note:'Portas ou gavetas e divisórias não foram escolhidas. O corte mostra o espaço reservado, sem inventar um interior aprovado.'},
 bathmirror:{title:'Armário espelhado raso',status:'Conteúdo definido; divisões pendentes',rows:[['Guardar','Escovas, pasta, desodorante e pequenos cosméticos.'],['Frente','Toda espelhada, sem nichos abertos; luz frontal para maquiagem.']],note:'Profundidade externa 12–15 cm é proposta. Dimensionar útil e possível canal de tubulação sem perder o armazenamento desejado.'},
 bench:{title:'Baú do banco do jantar',status:'Guarda funcional definida',rows:[['Conteúdo','Aspirador e itens grandes de apoio.']],note:'Medidas úteis, abertura e cabimento permanecem para detalhamento.'}
};
